services:
  db_app_vr:
    image: postgres
    container_name: db_app_vr
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_app_vr:/var/lib/postgresql/data
    
  node_app_vr:
    container_name: node_app_vr
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_app_vr
    env_file:
      - .env

volumes:
  pg_app_vr: